/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b8a2e397e8152b78b7ef060f5b63ee90)
interface __BaseEnv_Env {
	SKILL_STORE: KVNamespace;
	DB: D1Database;
	COLLECTION_LIMITER: RateLimit;
	BROWSER: BrowserRun;
	AI: Ai;
	ASSETS: Fetcher;
	SKILL_ADMIN_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SKILL_ADMIN_PASSWORD">> {}
}
