import test from 'node:test';
import assert from 'node:assert/strict';
import {pageSignals,rateSignals,verifyChannels} from '../cloudflare/channel-verification.js';
import {mergeVerification} from '../src/channel-verification.js';
test('dates require attributable content; copyrights, unrelated posts and future dates ignored',()=>{const html='<p>Copyright 2026</p><script type="application/ld+json">'+JSON.stringify([{'@type':'Organization',dateModified:'2026-09-10'},{'@type':'SocialMediaPosting',datePublished:'2026-09-09',author:{url:'https://instagram.com/other'}},{'@type':'SocialMediaPosting',datePublished:'2099-01-01',author:{url:'https://instagram.com/shop'}}])+'</script>';assert.equal(pageSignals(html,'https://instagram.com/shop').activities.length,0);});
test('login walls and unknown ownership cannot receive colors',()=>{const p=pageSignals('Log in to continue '+'x'.repeat(600),'https://instagram.com/shop');assert.equal(p.restricted,true);assert.equal(rateSignals([p],'Instagram',true).level,'unknown');assert.equal(rateSignals([{...p,restricted:false}],'Instagram',false).level,'unknown');});
test('recent attributable publications support activity but old articles do not establish inactivity',()=>{const date=new Date().toISOString();const html='<p>'+'business '.repeat(100)+'</p><script type="application/ld+json">'+JSON.stringify([1,2].map(i=>({'@type':'SocialMediaPosting',url:'https://instagram.com/p/'+i,datePublished:date,author:{url:'https://instagram.com/shop'}})))+'</script>';const p=pageSignals(html,'https://instagram.com/shop');assert.equal(rateSignals([p],'Instagram',true).level,'green');assert.equal(rateSignals([{...p,activities:[{date:'2020-01-01',url:p.url}]}],'Instagram',true).level,'unknown');});
test('toolkit links alone cannot establish complete operations',()=>{const p=pageSignals('<script type="application/ld+json">{"@type":"Organization","name":"Shop","logo":"logo.png"}</script>'+['shop','contact','booking','privacy'].map(x=>`<a href="/${x}">${x}</a>`).join('')+'business '.repeat(100),'https://example.com');assert.equal(rateSignals([p],'Website',true).level,'unknown');});
test('automatic discovery excludes share links and records access restrictions without inventing absence',async()=>{const r=await verifyChannels({id:'a',website:'https://example.com'},async url=>{if(url.includes('instagram'))throw Error('ACCESS_RESTRICTED');return {url,html:'<title>Shop</title><a href="https://facebook.com/sharer.php?u=a">Share</a><a href="https://instagram.com/shop">Account</a><a href="mailto:hello@example.com">Email</a>'};});const ig=r.body.checks.find(x=>x.platform==='Instagram');assert.equal(ig.ownership,'official_link');assert.equal(ig.level,'unknown');assert.equal(ig.access,'restricted');assert.equal(r.body.checks.find(x=>x.platform==='Facebook').access,'not_discovered');assert.equal(r.body.checks.find(x=>x.platform==='Email').contactability,'not_tested');});
test('verification merge preserves manual ratings and current notes while updating evidence',()=>{const customer={memo:'recent edit',notes:[{text:'reply'}],network:[],sources:[],channelRatings:{Website:{level:'orange',method:'manual'}},website:'https://example.com'};const patch=mergeVerification(customer,{verifiedAt:'2026-09-10',checks:[{platform:'Website',level:'unknown',method:'automatic'}],collection:{pages:[],links:[]}});assert.equal(patch.channelRatings.Website.level,'orange');assert.equal({...customer,...patch}.memo,'recent edit');assert.equal({...customer,...patch}.notes[0].text,'reply');});

test('hidden form JavaScript warnings do not reject substantive business pages',()=>{const html='<title>Teepee parties</title><div class="wpforms-hidden">Please enable JavaScript in your browser to complete this form.</div><p>'+'Children tent party services. '.repeat(30)+'</p>';assert.equal(pageSignals(html,'https://example.com').restricted,false);assert.equal(pageSignals('<p>Please enable JavaScript</p>','https://example.com').restricted,true);});

test('linked post dates must match the originating profile author',()=>{const post=author=>'<script type="application/ld+json">'+JSON.stringify({'@type':'SocialMediaPosting',url:'https://instagram.com/p/1',datePublished:'2026-01-01',author:{url:author}})+'</script>';assert.equal(pageSignals(post('https://instagram.com/other'),'https://instagram.com/p/1',Date.now(),'https://instagram.com/shop').activities.length,0);assert.equal(pageSignals(post('https://instagram.com/shop'),'https://instagram.com/p/1',Date.now(),'https://instagram.com/shop').activities.length,1);});
