import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {readWorkspace,writeWorkspace,validateWorkspace,databaseRequest} from '../cloudflare/database-api.js';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0001_workspace.sql',import.meta.url),'utf8'));return {sql,prepare(text){return {text,args:[],bind(...args){this.args=args;return this;}};},async batch(items){sql.exec('BEGIN');try{const result=items.map(x=>({results:sql.prepare(x.text).all(...x.args)}));sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
const sample=()=>({revision:0,customers:[{id:'a',name:'Customer',website:'https://example.com',memo:'keep',sources:[{url:'https://example.com',text:'evidence'}],contacts:[],network:[],notes:[{text:'reply'}],assessmentRuns:[{text:'old',ruleVersion:'v1',scoring:{score:85,coverage:65,dimensions:[{key:'fit',value:4,evidenceIds:['E1']}]}}],plan:{brief:'original'}}],projects:[{id:'p',product:['帐篷','Tents'],customerIds:['a'],deleted:true}],drafts:[{id:'d',customerId:'a',text:'draft'}]});
test('database round trip preserves linked evidence, history, tombstones and notes',async()=>{const db=database(),d=sample();assert.equal(validateWorkspace(d),true);assert.equal(await writeWorkspace(db,d),1);assert.deepEqual(await readWorkspace(db),{...d,revision:1});assert.equal(db.sql.prepare('SELECT count(*) n FROM evidence').get().n,1);});
test('stale writes roll back atomically and preserve latest data',async()=>{const db=database(),d=sample();await writeWorkspace(db,d);await assert.rejects(writeWorkspace(db,{...d,customers:[]}));assert.equal((await readWorkspace(db)).customers[0].memo,'keep');assert.equal((await readWorkspace(db)).revision,1);});
test('invalid project references and duplicate customer ids rejected',()=>{const d=sample();assert.equal(validateWorkspace({...d,customers:[...d.customers,...d.customers]}),false);assert.equal(validateWorkspace({...d,projects:[{id:'p',customerIds:['missing']}]}),false);});
test('database API requires login and rejects cross-origin writes',async()=>{const env={DB:database(),SKILL_ADMIN_PASSWORD:'test-only'};assert.equal((await databaseRequest(new Request('https://example.com/api/workspace'),env)).status,401);assert.equal((await databaseRequest(new Request('https://example.com/api/workspace',{method:'PUT',headers:{origin:'https://evil.example'}}),env)).status,403);const login=await databaseRequest(new Request('https://example.com/api/session',{method:'POST',body:JSON.stringify({password:'test-only'})}),env);const cookie=login.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);const r=await databaseRequest(new Request('https://example.com/api/workspace',{headers:{cookie}}),env);assert.equal(r.status,200);});
