import {authenticated} from './database-api.js';
export const aiProviders={gemini:{url:'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',model:'gemini-3.8-flash'},deepseek:{url:'https://api.deepseek.com/chat/completions',model:'deepseek-flash'},openai:{url:'https://api.openai.com/v1/chat/completions',model:'gpt-4.1-mini'}};
const slots=['places',...Object.keys(aiProviders)];
async function cryptoKey(env){if(!env.API_CONFIG_KEY)throw Error('CONFIG_STORAGE_UNAVAILABLE');return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(env.API_CONFIG_KEY)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function encryptConfig(value,env){const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptoKey(env),new TextEncoder().encode(JSON.stringify(value)));return JSON.stringify({iv:Array.from(iv),data:Array.from(new Uint8Array(data))});}
export async function readConfig(env){const text=await env.SKILL_STORE?.get('api-config');if(!text)return {provider:'cloudflare',keys:{},models:{}};const v=JSON.parse(text);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(v.iv)},await cryptoKey(env),new Uint8Array(v.data))));}
function metadata(c,env){return {configured:slots.reduce((v,k)=>({...v,[k]:!!(c.keys[k]||(k==='places'&&env.GOOGLE_MAPS_API_KEY))}),{}),provider:c.provider,models:{...Object.fromEntries(Object.entries(aiProviders).map(([k,v])=>[k,v.model])),...c.models},setupComplete:!!c.setupComplete,builtin:!!env.AI};}
export async function chat(provider,key,model,params,fetcher=fetch){const spec=aiProviders[provider];if(!spec||!key)throw Error('AI_NOT_CONFIGURED');let r;try{r=await fetcher(spec.url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},signal:AbortSignal.timeout(120000),body:JSON.stringify({model,messages:params.messages,stream:false,...(provider==='gemini'?{reasoning_effort:'low'}:{}),...(provider==='deepseek'?{max_tokens:params.max_tokens,thinking:{type:'disabled'}}:{max_completion_tokens:params.max_tokens})})});}catch{throw Error('PROVIDER_UNREACHABLE');}if(!r.ok)throw Error(r.status===401||r.status===403?'KEY_OR_PERMISSION_INVALID':r.status===429?'QUOTA_OR_RATE_LIMIT':r.status===404?'MODEL_NOT_AVAILABLE':'PROVIDER_REQUEST_FAILED');const d=await r.json(),choice=d.choices?.[0];if(choice?.finish_reason==='length')throw Error('AI_OUTPUT_TRUNCATED');const text=choice?.message?.content;if(typeof text!=='string'||!text.trim())throw Error('AI_EMPTY_RESPONSE');return {response:text};}
export async function configuredEnv(env){const c=await readConfig(env);if(c.provider==='cloudflare')return {...env,GOOGLE_MAPS_API_KEY:c.keys.places||env.GOOGLE_MAPS_API_KEY};const model=c.models[c.provider]||aiProviders[c.provider]?.model;return {...env,GOOGLE_MAPS_API_KEY:c.keys.places||env.GOOGLE_MAPS_API_KEY,AI_MODEL:c.provider+'/'+model,AI:c.keys[c.provider]?{run:(_,params)=>chat(c.provider,c.keys[c.provider],model,params)}:null};}
export async function integrationRequest(request,env,fetcher=fetch){const reply=(body,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});if(!await authenticated(request,env))return reply({code:'UNAUTHORIZED'},401);if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return reply({code:'FORBIDDEN'},403);try{const c=await readConfig(env);if(request.method==='GET')return reply(metadata(c,env));if(request.method!=='POST')return reply({code:'METHOD_NOT_ALLOWED'},405);const text=await request.text();if(text.length>16000)return reply({code:'INPUT_TOO_LARGE'},413);let input;try{input=JSON.parse(text);}catch{return reply({code:'INVALID_INPUT'},400);}if(input.action==='test'){if(env.COLLECTION_LIMITER){const limit=await env.COLLECTION_LIMITER.limit({key:'api-test:'+(request.headers.get('CF-Connecting-IP')||'unknown')});if(!limit.success)return reply({code:'QUOTA_OR_RATE_LIMIT'},429);}
 const p=input.provider;if(!slots.includes(p))return reply({code:'INVALID_PROVIDER'},400);if(input.key!==undefined&&(typeof input.key!=='string'||input.key.length>4096))return reply({code:'INVALID_KEY'},400);const key=input.key?.trim()||c.keys[p]||(p==='places'?env.GOOGLE_MAPS_API_KEY:null);if(!key)return reply({code:'KEY_REQUIRED'},400);
 if(p==='places'){let r;try{r=await fetcher('https://places.googleapis.com/v1/places:searchText',{method:'POST',signal:AbortSignal.timeout(20000),headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':'places.id'},body:JSON.stringify({textQuery:'museum London',pageSize:1})});}catch{return reply({code:'PROVIDER_UNREACHABLE'},502);}if(!r.ok)return reply({code:r.status===429?'QUOTA_OR_RATE_LIMIT':'PLACES_PERMISSION_OR_BILLING',upstreamStatus:r.status},502);
 }else{const model=input.model||c.models[p]||aiProviders[p].model;if(typeof model!=='string'||model.length>120)return reply({code:'INVALID_MODEL'},400);await chat(p,key,model,{messages:[{role:'user',content:'Reply with OK.'}],max_tokens:128},fetcher);}return reply({ok:true,provider:p});
 }
 if(input.action!=='save')return reply({code:'INVALID_ACTION'},400);if(!['cloudflare',...Object.keys(aiProviders)].includes(input.provider))return reply({code:'INVALID_PROVIDER'},400);const next={...c,keys:{...c.keys},models:{...c.models},provider:input.provider,setupComplete:true};for(const p of slots){const key=input.keys?.[p];if(key!==undefined){if(typeof key!=='string'||key.length>4096)return reply({code:'INVALID_KEY'},400);if(key.trim())next.keys[p]=key.trim();}if(input.remove?.includes(p))delete next.keys[p];if(aiProviders[p]&&input.models?.[p]!==undefined){const model=input.models[p];if(typeof model!=='string'||!/^[a-zA-Z0-9._:/-]{1,120}$/.test(model))return reply({code:'INVALID_MODEL'},400);next.models[p]=model;}}
 if(next.provider!=='cloudflare'&&!next.keys[next.provider])return reply({code:'KEY_REQUIRED'},400);if(!env.SKILL_STORE||!env.API_CONFIG_KEY)return reply({code:'CONFIG_STORAGE_UNAVAILABLE'},503);await env.SKILL_STORE.put('api-config',await encryptConfig(next,env));return reply(metadata(next,env));
 }catch(e){const allowed=['KEY_OR_PERMISSION_INVALID','QUOTA_OR_RATE_LIMIT','MODEL_NOT_AVAILABLE','PROVIDER_REQUEST_FAILED','PROVIDER_UNREACHABLE','AI_EMPTY_RESPONSE','AI_OUTPUT_TRUNCATED','CONFIG_STORAGE_UNAVAILABLE'];return reply({code:allowed.includes(e.message)?e.message:'CONFIG_REQUEST_FAILED'},502);}}
