import React,{useEffect,useRef,useState} from 'react';
import {levels} from './market';
import SourceLink from './SourceLink';
import {mergeVerification} from './channel-verification';
export default function ChannelVerification({customer,en,update}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),latest=useRef(customer),attempted=useRef(false);latest.current=customer;const t=(a,b)=>en?b:a,bi=v=>Array.isArray(v)?v[en?1:0]:v;
 async function run(){if(busy||customer.demo||!customer.website)return;setBusy(true);setError('');try{const r=await fetch('/api/verify-channels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:customer.id,website:customer.website})});const d=await r.json();if(!r.ok)throw Error(d.code);if(d.customerId!==customer.id)throw Error('CUSTOMER_MISMATCH');if(latest.current.website!==customer.website)return;update(customer.id,mergeVerification(latest.current,d));}catch(e){setError(t('自动核验未完成，已保留原记录。','Automatic verification did not finish; previous records preserved.')+' '+e.message);}finally{setBusy(false);}}
 useEffect(()=>{if(attempted.current||customer.demo||!customer.website)return;const v=customer.channelVerification;if(v?.website===customer.website&&Date.now()<(v.nextCheckAt?Date.parse(v.nextCheckAt):Date.parse(v.verifiedAt)+7*86400000))return;attempted.current=true;run();},[customer.id,customer.website]);
 const v=customer.channelVerification;
 return <div className="evidence"><div className="section-heading"><h3>{t('自动渠道核验','Automatic channel verification')}</h3><button className="btn secondary" onClick={run} disabled={busy||customer.demo||!customer.website}>{busy?t('核验中…','Verifying…'):t('重新核验','Verify again')}</button></div><p>{t('打开评估时自动核验，成功结果保留7天；读取受限时1小时后再次打开会重试。分别核对官网关联、页面可读取性与运营证据；不会发送邮件或消息。','Checks on opening; successful reads cached for 7 days, restricted reads retry on opening after 1 hour. Website association, page readability and operational evidence are separate. No emails or messages are sent.')}</p>{busy&&<p role="status">{t('正在读取官网及其公开关联渠道，请稍候…','Reading the website and its public channels…')}</p>}{error&&<p role="alert">{error}</p>}{v&&<><small>{t('最近核验：','Last checked: ')}{new Date(v.verifiedAt).toLocaleString(en?'en-GB':'zh-CN')}</small>{v.checks.map((check,i)=><div className="customer-source" key={check.platform+i}><h3>{check.platform} · {check.ownership==='official_link'?t('官网关联已核对','Website association checked'):t('关联未确认','Association unconfirmed')}</h3><p>{({read:t('页面读取成功','Page read'),restricted:t('页面受限或读取失败','Restricted or failed'),listed_not_tested:t('官网公开列出；未测试收件或消息接收','Published by website; message delivery not tested'),not_discovered:t('本轮未发现入口','No entry found in this scan'),unread:t('未读取到有效页面','No readable page')})[check.access]}{check.failure?' · '+(({ LOGIN_REQUIRED:t('平台要求登录授权','Platform login required'),BROWSER_ACCESS_RESTRICTED:t('浏览器加载仍被网站拒绝','Website also rejected browser loading'),BROWSER_QUOTA:t('浏览器额度暂不可用','Browser quota unavailable'),BROWSER_TIMEOUT:t('浏览器加载超时','Browser load timed out'),BROWSER_SCAN_LIMIT:t('本轮浏览器读取数量已达上限','Browser page budget reached'),BROWSER_UNAVAILABLE:t('浏览器服务暂不可用','Browser service unavailable')})[check.failure]||check.failure):''}</p><p>{t('运营评级：','Maturity: ')}{levels[check.level]?.[en?1:0]} · {bi(check.reason)}</p>{check.latestObservedPublication&&<p>{t('本轮观察到的最新发布日期：','Latest publication observed: ')}{check.latestObservedPublication.slice(0,10)}</p>}{check.url&&<SourceLink href={check.url} en={en}>{t('查看渠道','View channel')}</SourceLink>}<details><summary>{t('核验依据','Verification evidence')}</summary>{[...new Set([check.source,...check.sourceUrls||[]].filter(Boolean))].map(url=><SourceLink key={url} href={url} en={en}>{t('打开依据','View evidence')}</SourceLink>)}{(v.readAttempts||[]).filter(a=>a.url===check.url).map((a,j)=><p key={j}>{a.method==='browser'?t('浏览器加载','Browser loading'):t('网页直接读取','Direct page read')} · {a.status==='read'?t('成功','Succeeded'):t('未完成','Incomplete')}{a.code?' · '+a.code:''}</p>)}<small>{check.ruleVersion||'public-channel-evidence-v1'}</small></details></div>)}</>}</div>;
}
