import React,{useState,useEffect,useRef} from 'react';
import './cloud-workspace.css';
import {seed} from './data';
import {mergeResearchedCustomers,mergeResearchProject} from './researched-customers';
import {mergeDubaiCustomers,mergeDubaiProject} from './dubai-prospects';
import {initialProjects} from './market';
function initialWorkspace(){const customers=mergeDubaiCustomers(mergeResearchedCustomers(seed()));return {customers,projects:mergeDubaiProject(mergeResearchProject(initialProjects(customers.filter(c=>c.origin!=='public-research')),customers),customers),drafts:[]};}
function readLegacy(){try{return {customers:JSON.parse(localStorage.getItem('tg-customers')||'[]'),projects:JSON.parse(localStorage.getItem('tg-projects')||'[]'),drafts:JSON.parse(localStorage.getItem('tg-drafts')||'[]')};}catch{return null;}}
export default function CloudWorkspace({App}){
 const [workspace,setWorkspace]=useState(null),[password,setPassword]=useState(''),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[generation,setGeneration]=useState(0),[language,setLanguage]=useState(localStorage.getItem('tg-lang')||'zh');
 const toolbar=useRef(null),[barHeight,setBarHeight]=useState(44);
 useEffect(()=>{if(!workspace||!toolbar.current)return;const observer=new ResizeObserver(()=>setBarHeight(toolbar.current.getBoundingClientRect().height));observer.observe(toolbar.current);return()=>observer.disconnect();},[workspace]);
 const en=language==='en',t=(a,b)=>en?b:a,revision=useRef(0),pending=useRef(null),timer=useRef(null),saving=useRef(false),blocked=useRef(false),legacy=useRef(readLegacy()),baseline=useRef('');
 useEffect(()=>{const languageChange=()=>setLanguage(document.documentElement.lang.startsWith('en')?'en':'zh');const observer=new MutationObserver(languageChange);observer.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});if(legacy.current&&!localStorage.getItem('tg-before-database'))localStorage.setItem('tg-before-database',JSON.stringify(legacy.current));load();const before=e=>{if(pending.current||saving.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>{observer.disconnect();clearTimeout(timer.current);window.removeEventListener('beforeunload',before);};},[]);
 async function load(){try{const r=await fetch('/api/workspace');if(r.status===401){setStatus('login');return;}if(!r.ok)throw Error('LOAD_FAILED');const d=await r.json();revision.current=d.revision;const value=d.revision===0&&d.customers.length===0?initialWorkspace():d;baseline.current=JSON.stringify({customers:value.customers,projects:value.projects,drafts:value.drafts});setWorkspace(value);setStatus('saved');if(d.revision===0)queue(value);}catch{setStatus('error');setError(t('数据库连接失败，请重试。','Database connection failed. Please retry.'));}}
 async function login(e){e.preventDefault();setError('');try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw Error();setPassword('');await load();}catch{setError(t('登录失败，请核对密码；多次尝试后请稍候。','Login failed. Check your password; wait after repeated attempts.'));}}
 function queue(value){const data={customers:value.customers,projects:value.projects,drafts:value.drafts};pending.current=data;setStatus('pending');clearTimeout(timer.current);timer.current=setTimeout(save,650);}
 function change(data){const text=JSON.stringify(data);if(text===baseline.current)return;baseline.current=text;queue(data);}
 async function save(){if(saving.current||blocked.current||!pending.current)return;saving.current=true;const data=pending.current;pending.current=null;setStatus('saving');try{const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,revision:revision.current})});if(!r.ok)throw Error(r.status===409?'conflict':r.status===401?'session':'save');const d=await r.json();revision.current=d.revision;setStatus(pending.current?'pending':'saved');}catch(e){pending.current=pending.current||data;blocked.current=true;setStatus('error');setError(e.message==='conflict'?t('其他设备已更新资料。请先导出本页备份，再刷新读取最新版；系统不会覆盖对方修改。','Another device updated this workspace. Export this page before refreshing; remote changes will not be overwritten.'):t('尚未保存到数据库。请保留页面并重试；登录过期时请先导出备份再刷新登录。','Not saved. Keep this page and retry; if your session expired, export a backup before signing in again.'));}finally{saving.current=false;if(pending.current&&!blocked.current)save();}}
 function exportBackup(){const data=pending.current||JSON.parse(baseline.current);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='find-prospects-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function importLegacy(){let old;try{old=JSON.parse(localStorage.getItem('tg-before-database'));}catch{}if(!old?.customers?.length)return;if(!confirm(t('将旧浏览器资料合并到数据库。同一客户以旧资料为准，云端独有客户保留。继续？','Merge browser backup into the database? Matching records use browser values; cloud-only records remain.')))return;const now=JSON.parse(baseline.current),merge=(a,b)=>[...new Map([...a,...b].map(v=>[v.id,v])).values()];const value={customers:merge(now.customers,old.customers),projects:merge(now.projects,old.projects||[]),drafts:merge(now.drafts,old.drafts||[])};setWorkspace(value);setGeneration(x=>x+1);baseline.current=JSON.stringify(value);queue(value);}
 if(!workspace)return <main style={{maxWidth:440,margin:'12vh auto',padding:28}}><h1>{t('远见 · 云端工作区','Farview · Cloud workspace')}</h1><button className="text-btn" onClick={()=>setLanguage(en?'zh':'en')}>中 / EN</button><p>{t('客户、项目和评估统一保存在数据库。使用现有 Skill 管理密码登录。','Customers, projects and assessments share one database. Sign in with your existing Skill admin password.')}</p>{status==='login'?<form onSubmit={login}><label>{t('工作区密码','Workspace password')}<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="btn" type="submit">{t('登录','Sign in')}</button></form>:<button className="btn" onClick={load}>{t('连接数据库 / 重试','Connect / Retry')}</button>}{error&&<p role="alert">{error}</p>}</main>;
 return <div className="cloud-shell" style={{'--cloud-offset':barHeight+'px'}}><div ref={toolbar} style={{position:'sticky',top:0,zIndex:1000,background:'#e8f6f5',padding:'8px 20px',display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}><strong>{t('云端数据库','Cloud database')} · {({saved:t('已保存','Saved'),pending:t('等待保存','Pending'),saving:t('保存中…','Saving…'),error:t('未同步','Not synced')})[status]}</strong><button className="text-btn" onClick={exportBackup}>{t('导出备份','Export backup')}</button><button className="text-btn" disabled={saving.current||status==='error'} onClick={importLegacy}>{t('导入原浏览器资料','Import browser records')}</button><button className="text-btn" onClick={()=>{if(pending.current||saving.current){alert(t('请先等待保存完成或导出备份。','Wait for saving or export a backup first.'));return;}location.reload();}}>{t('刷新云端资料','Refresh cloud data')}</button><button className="text-btn" onClick={async()=>{if(pending.current||saving.current)return;await fetch('/api/session',{method:'DELETE'});location.reload();}}>{t('退出','Sign out')}</button>{error&&<span role="alert">{error} <button onClick={()=>{blocked.current=false;setError('');save();}}>{t('重试保存','Retry save')}</button></span>}</div><App key={generation} workspace={workspace} onWorkspaceChange={change}/></div>;
}
