import React from 'react';
import {ArrowLeft,ExternalLink,Download} from 'lucide-react';
import {ChannelRatings} from './Market.jsx';
import {scoreFor,exportPlan} from './domain';
import {phaseNames,phases} from './market';
import './assessment.css';

export default function CustomerAssessment({customer:c,en,onBack,update,download}){
 const t=(a,b)=>en?b:a,bi=v=>Array.isArray(v)?v[en?1:0]:v;
 const missing=t('尚未取得资料，待核实。','No information available; verification needed.');
 const plan=c.plan||{keywords:'',brief:'',items:[],saved:false};
 const sections=[['facts','客户概况与来源','Profile & sources'],['fit','适配分析','Fit analysis'],['channels','渠道状态','Channels'],['proposal','产品与素材建议','Product & materials'],['followup','沟通跟进','Follow-up']];
 return <article className="assessment"><div className="assessment-back"><button onClick={onBack}><ArrowLeft size={16}/>{t('返回客户列表','Back to customers')}</button><span>{c.demo?t('演示客户 · 非真实业务评估','Demo customer · Not a real evaluation'):c.origin==='public-research'?t('公开资料研究 · 未联系客户','Public research · Not contacted'):t('客户资料评估 · AI 尚未运行','Customer assessment · AI not run')}</span></div>
 <header className="assessment-header"><div className="assessment-monogram">{c.name.slice(0,2)}</div><div className="assessment-title"><h1>{c.name}</h1><p>{bi(c.country)} · {bi(c.type)}</p><div className="assessment-tags"><span>{phaseNames[phases.indexOf(c.stage)]?.[en?1:0]||t('已删除','Deleted')}</span><span>{c.tags||t('暂无标签','No tags')}</span></div></div><button className="btn secondary" onClick={()=>download({...exportPlan({...c,plan}),memo:c.memo||'',notes:c.notes||[]},c.name+'-assessment.json')}><Download size={16}/>{t('导出客户评估','Export assessment')}</button></header>
 <div className="assessment-summary"><div><h2>{t('当前判断','Current assessment')}</h2><p>{bi(c.reason)||missing}</p><small>{t('以上为待确认的判断，不代表客户已表达采购需求。','This is an unconfirmed assessment, not a purchase requirement expressed by the customer.')}</small></div><div className="assessment-confidence"><span>{c.demo?t('示例评分','Demo score'):t('AI 评分','AI score')}</span><strong>{scoreFor(c)??t('待评估','Unrated')}</strong><small>{t('按当前客户资料展示','Based on this customer’s record')}</small></div></div>
 <nav className="assessment-nav" aria-label={t('评估目录','Assessment sections')}>{sections.map(([id,zh,eng])=><a key={id} href={'#ca-'+id} onClick={e=>{e.preventDefault();document.getElementById('ca-'+id)?.scrollIntoView({behavior:'smooth'});}}>{t(zh,eng)}</a>)}</nav>
 <div className="assessment-layout"><div className="assessment-main"><section id="ca-facts" className="assessment-section"><h2>{t('客户概况与原始依据','Customer profile & original evidence')}</h2><dl className="customer-facts"><dt>{t('区域','Region')}</dt><dd>{bi(c.country)||missing}</dd><dt>{t('场馆区域','Venue area')}</dt><dd>{bi(c.area)||missing}</dd><dt>{t('客户类型','Business type')}</dt><dd>{bi(c.type)||missing}</dd><dt>{t('官网','Website')}</dt><dd>{c.website?<a className="assessment-source" href={c.website} target="_blank" rel="noreferrer">{c.website}<ExternalLink size={13}/></a>:missing}</dd><dt>{t('研究核对日期','Research reviewed')}</dt><dd>{c.reviewedAt||missing}</dd><dt>{t('采集时间','Collection time')}</dt><dd>{c.lastCollected?new Date(c.lastCollected).toLocaleString(en?'en-GB':'zh-CN'):t('未记录，不推定为今天','Not recorded; not assumed to be today')}</dd></dl>
 {(c.sources||[]).map((s,i)=><div className="customer-source" key={i}><span className="evidence-kind fact">{c.demo?t('演示依据','Demo evidence'):t('已收录来源 · 内容需核验','Recorded source · Verify content')}</span><h3>{bi(s.title)}</h3><p>{bi(s.text)}</p>{s.url?<a className="assessment-source" href={s.url} target="_blank" rel="noreferrer">{t('打开原始来源','Open original source')} <ExternalLink size={13}/></a>:<small>{t('暂无可核验的来源链接','No verifiable source link')}</small>}</div>)}{!c.sources?.length&&<p>{missing}</p>}</section>
 {c.contacts?.length>0&&<section className="assessment-section"><h2>{t('公开联系入口','Public contact details')}</h2>{c.contacts.map((v,i)=><div className="customer-source" key={i}><h3>{v.type}: {v.value}</h3><p>{bi(v.note)}</p><a className="assessment-source" href={v.source} target="_blank" rel="noreferrer">{t('核对联系方式来源','Verify contact source')}</a></div>)}</section>}<section id="ca-fit" className="assessment-section"><h2>{t('为什么可能适合','Why this customer may fit')}</h2><span className="evidence-kind hypothesis">{t('需求推测 · 待确认','Hypothesis · Unconfirmed')}</span><p>{bi(c.reason)||missing}</p>{c.research?.concern&&<div className="customer-source"><h3>{t('降低确定性的因素','Uncertainties')}</h3><p>{bi(c.research.concern)}</p><h3>{t('建议方案 · 待确认','Suggested approach · Unconfirmed')}</h3><p>{bi(c.research.proposal)}</p></div>}<div className="assessment-reasons"><div><h3>{t('当前能支持的判断','What current evidence supports')}</h3><p>{t('请结合上方原始来源核实业务与产品场景。现有结论尚未经过正式 AI 规则评估。','Check the original sources against the business and product use case. Formal AI assessment has not run.')}</p></div><div><h3>{t('还不能确认','Still unknown')}</h3><p>{t('采购计划、负责人、预算、数量、场地条件与时间均需通过真实沟通确认。','Buying plans, owner, budget, quantity, space and timing require actual communication.')}</p></div></div></section>
 <section id="ca-channels" className="assessment-section"><h2>{t('渠道与运营证据','Channels & operational evidence')}</h2><ChannelRatings customer={c} en={en}/><p>{t('悬停或聚焦图标查看评级理由；找到链接不等于已确认可以联系。','Hover or focus an icon for rating evidence. A link does not prove reachability.')}</p><div className="assessment-channel-list">{(c.network||[]).map((n,i)=><div key={n.id||i}><strong>{n.platform}</strong><span>{n.confirmed?t('来源关联','Source-linked'):t('关联待核验','Unverified link')}</span><p>{bi(n.evidence)||missing}{n.url&&<><br/><a className="assessment-source" href={n.url} target="_blank" rel="noreferrer">{t('打开渠道','Open channel')} <ExternalLink size={13}/></a></>}</p></div>)}</div>{!c.network?.length&&<p>{missing}</p>}</section>
 <section id="ca-proposal" className="assessment-section"><h2>{t('产品建议与软件一需求','Product proposal & material brief')}</h2><p>{t('仅记录此客户的制作方向。尚未填写的内容保持为空，不套用其他客户的方案。','Record this customer’s requirements. Missing content stays empty; another customer’s proposal is never substituted.')}</p><label className="field-label">{t('场景与关键词','Scenes & keywords')}<textarea rows="2" value={plan.keywords} onChange={e=>update(c.id,{plan:{...plan,keywords:e.target.value,saved:false}})}/></label><label className="field-label">{t('建议方案与制作说明','Proposal & production brief')}<textarea rows="4" value={plan.brief} placeholder={t('待补充产品方向、使用场景及需要工厂确认的条件…','Add the concept, use case and factory checks…')} onChange={e=>update(c.id,{plan:{...plan,brief:e.target.value,saved:false}})}/></label><p>{t('计划制作：','Planned materials: ')}{plan.items?.join(' / ')||t('尚未确定','Not defined')}</p><button className="btn secondary" onClick={()=>update(c.id,{plan:{...plan,saved:true}})}>{plan.saved?t('计划已保存','Plan saved'):t('确认保存计划','Save plan')}</button><small>{t('修改保存在当前浏览器；未发送给软件一。','Changes stay in this browser; not sent to software one.')}</small></section>
 <section id="ca-followup" className="assessment-section"><h2>{t('人工判断与沟通记录','Team assessment & communication')}</h2><label className="field-label">{t('人工备注','Team notes')}<textarea aria-label={t('人工备注','Team notes')} rows="4" value={c.memo||''} placeholder={t('填写该客户的下一步行动或已确认的回复…','Record this customer’s next action or confirmed reply…')} onChange={e=>update(c.id,{memo:e.target.value})}/></label><label className="field-label">{t('客户标签','Customer tags')}<input value={c.tags||''} onChange={e=>update(c.id,{tags:e.target.value})}/></label><small>{t('自动保存到当前浏览器，与客户列表同步。','Automatically saved in this browser and synced with the customer list.')}</small>{(c.notes||[]).map((n,i)=><div className="customer-source" key={i}><small>{new Date(n.at).toLocaleString(en?'en-GB':'zh-CN')}</small><p>{n.text}</p></div>)}{!c.notes?.length&&<p>{t('暂无沟通记录，不能据此推定客户已经有意向。','No communication recorded. Buying intent cannot be assumed.')}</p>}</section></div>
 <aside className="assessment-sidebar"><h3>{t('评估对象','Assessment subject')}</h3><p className="assessment-decision">{c.name}</p><p>{t('所有来源、备注与方案均绑定这位客户。','Sources, notes and proposals belong to this customer.')}</p><hr/><h3>{t('仍需补齐','Information still needed')}</h3><ul className="customer-missing"><li>{t('真实采购需求','Actual buying need')}</li><li>{t('采购负责人和联系方式','Buyer and contact details')}</li><li>{t('预算、数量与时间','Budget, quantity and timing')}</li><li>{t('工厂可制造性确认','Factory feasibility confirmation')}</li></ul><small>{t('完整评估页已可用，不代表所有评估内容都已生成。','The full assessment page is available; its analysis is not automatically complete.')}</small></aside></div></article>;
}
