import React from 'react';
import './score.css';
const names={fit:['用途适配','Product fit'],demand:['需求强度','Demand'],role:['采购角色','Buying role'],potential:['商业潜力','Commercial potential'],timing:['采购时机','Timing'],reach:['可触达性','Reachability'],delivery:['交付匹配','Delivery fit']};
const priorities={priority:['优先跟进','Prioritize'],explore:['探索联系','Explore'],defer:['暂缓投入','Defer'],pending:['暂不足以评分','Insufficient evidence']};
const confidence={high:['高','High'],medium:['中','Medium'],low:['低','Low']};
export default function CustomerScore({customer:c,en,compact=false}){
 const t=(a,b)=>en?b:a,bi=v=>Array.isArray(v)?v[en?1:0]:v;
 const run=c.assessmentRuns?.at(-1),s=run?.scoring,previous=c.assessmentRuns?.slice(0,-1).reverse().find(r=>r.scoring)?.scoring;
 if(c.demo)return <div className="potential-compact"><strong>{c.scores?.reduce((a,b)=>a+b,0)??'—'}</strong><small>{t('演示分 · 非真实评估','Demo score · Not a real assessment')}</small></div>;
 if(!s)return <div className={compact?'potential-compact':'potential-panel'}><strong>{t('尚未评分','Not scored')}</strong><p>{t('点击「生成完整评估」获取评分及依据。','Generate a full assessment to obtain evidence-based scoring.')}</p></div>;
 const strongest=s.dimensions.filter(d=>d.value!==null).sort((a,b)=>b.value-a.value)[0];
 const changed=previous?s.dimensions.filter(d=>previous.dimensions.find(p=>p.key===d.key)?.value!==d.value):[];
 return <section className={compact?'potential-compact':'potential-panel'} aria-label={t('合作潜力评分','Collaboration potential score')}><div className="potential-overview"><div><small>{t('合作潜力 · 暂定','Collaboration potential · Provisional')}</small><div className="potential-number">{s.score??'—'}{s.score!==null&&<span>/100</span>}</div></div><div><b className={'potential-priority '+s.priority}>{bi(priorities[s.priority])}</b><p>{t('证据可信度','Evidence confidence')}：{bi(confidence[s.confidence])} · {t('覆盖','Coverage')} {s.coverage}%</p>{strongest&&<p className="potential-reason">{bi(strongest.reason)}</p>}{s.status==='failed'&&<small>{t('本轮评分未完成，可重新生成；报告已保留。','Scoring incomplete. Regenerate to retry; the report is retained.')}</small>}</div></div>{!compact&&<><p className="potential-note">{t('按已知维度加权计算；未知项不计零分。用于跟进排序，不代表成交概率。可信度反映证据覆盖与来源分布，不等于事实已独立核实。','Weighted over known dimensions; unknowns are not zero. This ranks follow-up priority, not conversion probability. Confidence reflects coverage and source distribution, not independent verification.')}</p><details><summary>{t('查看七维评分与来源','View seven dimensions and sources')}</summary><div className="potential-dimensions">{s.dimensions.map(d=><div key={d.key}><div className="potential-dimension-title"><b>{bi(names[d.key])}</b><span>{d.value===null?t('未知 · 不计分','Unknown · Not scored'):d.value+' / 4'} · {t('权重','Weight')} {d.weight}%</span></div><p>{bi(d.reason)}</p><small>{t('待确认','To confirm')}：{bi(d.gap)}</small><div>{d.evidenceIds.map(id=>{const source=run.sources.find(x=>x.id===id);return source&&<a key={id} href={source.url} target="_blank" rel="noreferrer">{id} ↗ </a>;})}</div></div>)}</div></details>{previous&&<p className="potential-note">{t('上次','Previous')} {previous.score??'—'} → {t('本次','Current')} {s.score??'—'} · {changed.length?t('变化维度：','Changed: ')+changed.map(d=>bi(names[d.key])).join(' / '):t('维度判断未变化；差异可能来自评分规则调整。','Dimension values unchanged; any difference may reflect scoring-rule changes.')}</p>}<small>{t('评估时间','Assessed')}：{new Date(run.generatedAt).toLocaleString(en?'en-GB':'zh-CN')}</small></>}</section>;
}
