const network=[{id:'web',platform:'Website',confirmed:true},{id:'maps',platform:'Google Maps',confirmed:true},{id:'fb',platform:'Facebook',confirmed:true},{id:'ig',platform:'Instagram',confirmed:true},{id:'li',platform:'LinkedIn',confirmed:false}];
const definitions=[
['Maple Nest Kids','英国','United Kingdom','儿童家居品牌','Children’s homewares',51.523,-.128,'finalist',[35,28,23],'阅读角新品预告，可能需要配套帐篷。','A reading-corner launch may call for complementary play tents.'],
['Little Meadow Living','德国','Germany','家居零售商','Home retailer',51.51,-.15,'shortlist',[33,27,22],'新增加儿童房系列，可核实帐篷品类计划。','A new children’s room range is a reason to ask about tent sourcing.'],
['Sprout Room Studio','英国','United Kingdom','亲子空间设计','Family space design',51.538,-.095,'shortlist',[31,26,21],'亲子空间项目可能有场景定制需求。','Family-space projects may benefit from custom play environments.'],
['Kindred Toy House','英国','United Kingdom','玩具零售商','Toy retailer',51.493,-.115,'qualified',[29,25,21],'已有角色扮演品类，可沟通补充产品。','An existing role-play range offers a potential product fit.'],
['Coastal Play Co.','澳大利亚','Australia','户外用品商','Outdoor retailer',51.506,-.074,'initial',[27,23,20],'正在展示亲子庭院用品，采购意向待确认。','Family garden products are featured; buying intent is unconfirmed.'],
['Willow & Small','英国','United Kingdom','儿童家居品牌','Children’s homewares',51.55,-.18,'initial',[30,24,20],'自然风格的儿童家居系列值得进一步核实。','A natural-style children’s range merits further research.'],
['Paper Moon Play','英国','United Kingdom','玩具零售商','Toy retailer',51.48,-.19,'initial',[28,22,19],'公开资料较少，需要进一步采集。','Limited public information; further collection is needed.'],
['Fern Family Spaces','英国','United Kingdom','亲子空间设计','Family space design',51.56,-.08,'initial',[32,24,21],'有亲子空间展示案例，待确认项目计划。','Family-space portfolio examples; project timing is unknown.']];
export function seed(){return definitions.map((d,i)=>({id:'demo-'+i,name:d[0],country:[d[1],d[2]],type:[d[3],d[4]],lat:d[5],lng:d[6],stage:d[7],scores:d[8],reason:[d[9],d[10]],demo:true,website:null,status:'uncontacted',notes:[],sources:[{kind:'website',title:['官网产品栏目（演示）','Website product range (demo)'],text:['品牌展示儿童阅读与游戏空间。','The brand features children’s reading and play spaces.'],url:null},{kind:'facebook',title:['Facebook 主页（演示）','Facebook page (demo)'],text:['社交页面中出现儿童空间主题。','Social content features children’s spaces.'],url:null}],network:network.map(n=>({...n,url:null,source:n.id==='fb'||n.id==='ig'?'web':'customer',evidence:n.confirmed?['官网互链示例，尚非真实采集','Example cross-link; not a live collection']:['同名账号，关联待核验','Matching name; association unverified']})),plan:{keywords:'儿童阅读角 / Reading corner, 自然配色 / Natural palette',brief:'',items:['Mockup','PDF / PPT'],saved:false},handoff:false}));}
