import CustomerScore from './CustomerScore.jsx';
import React,{useState} from 'react';
import {Mail,MessageCircle,Globe,Instagram,Facebook,Linkedin,Plus,ArrowUpRight,MoreHorizontal} from 'lucide-react';
import {phases,phaseNames,levels,channelRating,projectMembers,phaseCounts} from './market';
import {scoreFor} from './domain';
const channels=[['Email',Mail],['WhatsApp',MessageCircle],['Website',Globe],['Instagram',Instagram],['Facebook',Facebook],['LinkedIn',Linkedin]];
export function ChannelRatings({customer,en}){return <div className="channel-ratings">{channels.map(([name,Icon])=>{const r=channelRating(customer,name);const label=[name,r.ownership==='official_link'?(en?'Website association checked':'官网关联已核对'):'',levels[r.level][en?1:0],r.demo?(en?'Example rating, not collected':'示例评级，未实际采集'):(Array.isArray(r.reason)?r.reason[en?1:0]:(r.reason||'')),r.updatedAt||'',r.source||''].filter(Boolean).join(' · ');return <span key={name} tabIndex="0" className={'rating rating-'+r.level} aria-label={label}><Icon size={16}/>{r.ownership==='official_link'&&<sup aria-hidden="true" style={{position:'absolute',right:0,top:-6,color:'#008d9c'}}>✓</sup>}<span className="rating-tooltip">{label}</span></span>;})}</div>;}
export function Market({page,en,demoMode,customers,projects,setProjects,active,setActive,update,openAssessment,onMap,search}){
 const t=(a,b)=>en?b:a,bi=v=>Array.isArray(v)?v[en?1:0]:v;
 const [sort,setSort]=useState('original');
 const [phase,setPhase]=useState('all'),[form,setForm]=useState(false),[product,setProduct]=useState(''),[area,setArea]=useState(''),[menu,setMenu]=useState(null);
 const project=projects.find(p=>p.id===active),rows=project?projectMembers(project,customers):customers;
 const counts=phaseCounts(rows),visible=rows.filter(c=>(phase==='all'?c.stage!=='excluded':c.stage===phase)&&(!search||(c.name+' '+bi(c.country)+' '+(c.tags||'')).toLowerCase().includes(search.toLowerCase())));
 if(sort==='score')visible.sort((a,b)=>(scoreFor(b)??-1)-(scoreFor(a)??-1));
 const board=page==='dashboard';
 function enter(p){setActive(p.id);setPhase('all');}
 return <section className="market-workspace"><div className="page-heading"><div><span className="eyebrow">{t('市场开发 / 工作台','MARKET DEVELOPMENT / WORKSPACE')}</span><h1>{board?t('获客项目看板','Acquisition projects'):project?`${bi(project.product)} · ${bi(project.region)}`:t('客户档案','Customer directory')}</h1><p>{board?t('按产品与区域推进业务，让每一位客户都有明确的下一步。','Organize by product and region. Give every prospect a clear next step.'):t('对比渠道成熟度与适配依据，筛选、备注并持续跟进。','Compare channel maturity and fit evidence. Qualify, annotate and follow up.')}</p></div><button className="btn" onClick={()=>board?setForm(!form):onMap()}><Plus size={16}/>{board?t('新建获客项目','New project'):t('地图添加客户','Add from map')}</button></div>
 {form&&board&&<form className="panel project-form" onSubmit={e=>{e.preventDefault();const p={id:crypto.randomUUID(),product:product.trim(),region:area.trim(),createdAt:new Date().toISOString(),demo:demoMode,customerIds:[]};setProjects(ps=>[...ps,p]);setProduct('');setArea('');setForm(false);}}><label>{t('产品 / 服务','Product / service')}<input required maxLength="100" value={product} onChange={e=>setProduct(e.target.value)}/></label><label>{t('目标区域','Target region')}<input required maxLength="100" value={area} onChange={e=>setArea(e.target.value)}/></label><button className="btn" disabled={!product.trim()||!area.trim()}>{t('创建项目','Create project')}</button></form>}
 {board?<div className="panel table-wrap market-table"><table><thead><tr>{[t('产品 / 服务','Product / service'),t('区域','Region'),t('创建日期','Created'),t('候选 / 初选 / 重点 / 跟进','Candidates / Qualified / Priority / Follow-up'),t('操作','Actions')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><strong>{bi(p.product)}</strong><small>{p.demo?t('演示项目','Demo project'):p.origin==='public-research'?t('公开资料研究 · 非自动采集','Public research · Not automated'):t('获客项目','Acquisition project')}</small></td><td>{bi(p.region)}</td><td>{p.createdAt?new Date(p.createdAt).toLocaleDateString(en?'en-GB':'zh-CN'):t('历史导入 · 日期未知','Imported · Date unknown')}</td><td><div className="project-counts">{phaseCounts(projectMembers(p,customers)).map((n,i)=><span key={i} title={phaseNames[i][en?1:0]}>{n}</span>)}</div></td><td><div className="row-actions"><button className="text-btn" onClick={()=>enter(p)}>{t('详情','Details')} <ArrowUpRight size={14}/></button><button aria-label={t('更多操作','More actions')} onClick={()=>setMenu(menu===p.id?null:p.id)}><MoreHorizontal size={19}/></button>{menu===p.id&&<><button className="text-btn" onClick={()=>{setActive(p.id);onMap();}}>{t('地图添加','Add from map')}</button><button className="text-btn danger" onClick={()=>{if(!window.confirm(t('删除此项目？客户档案、评估和沟通记录会保留。','Delete this project? Customer profiles, assessments and messages will be kept.')))return;setProjects(ps=>ps.map(x=>x.id===p.id?{...x,deleted:true,customerIds:[]}:x));setMenu(null);if(active===p.id)setActive(null);}}>{t('删除项目','Delete project')}</button></>}</div></td></tr>)}</tbody></table>{!projects.length&&<div className="empty">{t('暂无项目，先创建产品与目标区域。','No projects yet. Create a product and target region.')}</div>}</div>:<>
 <div className="filter-toolbar"><select aria-label={t('排序','Sort')} value={sort} onChange={e=>setSort(e.target.value)}><option value="original">{t('默认排序','Default order')}</option><option value="score">{t('合作潜力从高到低','Potential: high to low')}</option></select><select aria-label={t('获客项目','Acquisition project')} value={active||''} onChange={e=>{setActive(e.target.value||null);setPhase('all');}}><option value="">{t('全部客户','All customers')}</option>{projects.map(p=><option key={p.id} value={p.id}>{bi(p.product)} · {bi(p.region)}</option>)}</select><button className="text-btn" onClick={()=>setPhase('all')}>{t('全部有效客户','All active customers')} ({rows.filter(c=>c.stage!=='excluded').length})</button><button className="text-btn" onClick={()=>setPhase('excluded')}>{t('已删除 / 恢复','Deleted / Restore')}</button></div>
 <div className="stage-tabs">{phases.map((s,i)=><button key={s} className={phase===s?'active':''} onClick={()=>setPhase(s)}><span>{phaseNames[i][en?1:0]}</span><strong>{counts[i]}</strong></button>)}</div>
 <div className="rating-legend">{Object.entries(levels).map(([key,label])=><span key={key}><i className={'dot rating-'+key}/>{label[en?1:0]}</span>)}</div>
 <div className="panel table-wrap market-table customer-matrix"><table><thead><tr>{[t('客户 / 区域','Customer / Region'),t('资料完整度','Channel maturity'),t('AI 适配分析','AI fit analysis'),t('合作潜力','Collaboration potential'),t('人工备注','Team notes'),t('标签','Tags'),t('操作','Actions')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><button className="customer-name" onClick={()=>openAssessment(c.id)}>{c.name}</button><small>{bi(c.country)}</small><span className="chip">{phaseNames[phases.indexOf(c.stage)]?.[en?1:0]||t('已删除','Deleted')}</span></td><td><ChannelRatings customer={c} en={en}/><small>{c.demo?t('示例评级','Example ratings'):t('以来源证据为准','Source evidence required')}</small></td><td className="fit-cell">{bi(c.reason)}<small>{c.demo?t('演示分析 · 待确认','Demo analysis · Unconfirmed'):(c.origin==='public-research'?t('研究建议 · 需求待确认','Research suggestion · Unconfirmed demand'):t('AI 尚未接入','AI not connected'))}</small></td><td><CustomerScore customer={c} en={en} compact/></td><td><textarea rows="2" aria-label={`${c.name} ${t('人工备注','Team notes')}`} value={c.memo||''} placeholder={t('记录接触背景…','Contact context…')} onChange={e=>update(c.id,{memo:e.target.value})}/></td><td><input aria-label={`${c.name} ${t('标签','Tags')}`} value={c.tags||''} placeholder={t('如：展会客户','e.g. Trade show')} onChange={e=>update(c.id,{tags:e.target.value})}/></td><td><div className="matrix-actions"><button className="text-btn" onClick={()=>openAssessment(c.id)}>{t('完整评估','Full assessment')}</button>{c.stage==='excluded'?<button className="text-btn" onClick={()=>update(c.id,{stage:c.previousStage||'initial'})}>{t('恢复','Restore')}</button>:<><select aria-label={`${c.name} ${t('阶段','Stage')}`} value={c.stage} onChange={e=>update(c.id,{stage:e.target.value})}>{phases.map((s,i)=><option key={s} value={s}>{phaseNames[i][en?1:0]}</option>)}</select>{!['shortlist','finalist'].includes(c.stage)&&<button className="text-btn" onClick={()=>update(c.id,{stage:'shortlist'})}>{t('加入重点','Prioritize')}</button>}<button className="text-btn danger" onClick={()=>update(c.id,{previousStage:c.stage,stage:'excluded'})}>{t('删除','Delete')}</button></>}</div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">{t('当前阶段没有客户','No customers in this stage')}</div>}</div><p className="muted">{t('删除可恢复；阶段由人工确认。生成完整评估后更新评分；分数仅用于跟进排序。','Deletion is reversible; stages are team-controlled. Generate full assessments to update scores; scores rank follow-up priority.')}</p></>}
 </section>;
}
