import React,{useState,useEffect} from 'react';
import {ArrowLeft,ExternalLink,CheckCircle2,HelpCircle,ArrowRight,Download,MapPin,Phone,Bookmark} from 'lucide-react';
import './assessment.css';
const party='https://orangewheels.com/en/parties-events';
const contact='https://orangewheels.com/en/contact';
const image='https://ik.imagekit.io/jdrmgoavu/orange-wheels/production/media/ow-birthday_themes_for_web-04_iJVAfzWXzY.png?tr=w-500';
const sections=[['overview','客户概况','Overview'],['evidence','为什么值得跟进','Fit evidence'],['channels','渠道与证据','Channels'],['proposal','建议卖什么','Proposal'],['next','下一步行动','Next steps'],['brief','交给软件一','Material brief']];
export default function OrangeAssessment({en,onBack}){
 const t=(a,b)=>en?b:a;
 const [saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem('tg-orange-assessment'))||{note:'',priority:false};}catch{return {note:'',priority:false};}}),[note,setNote]=useState(saved.note),[message,setMessage]=useState(''),[failedImage,setFailedImage]=useState(false),[imageLoaded,setImageLoaded]=useState(false);
 useEffect(()=>{if(!message)return;const id=setTimeout(()=>setMessage(''),4000);return()=>clearTimeout(id);},[message]);
 useEffect(()=>{if(imageLoaded)return;const id=setTimeout(()=>setFailedImage(true),8000);return()=>clearTimeout(id);},[imageLoaded]);
 const save=value=>{try{localStorage.setItem('tg-orange-assessment',JSON.stringify(value));setSaved(value);setMessage(t('已保存到当前浏览器','Saved in this browser'));}catch{setMessage(t('保存失败，请检查浏览器存储空间','Save failed. Check browser storage.'));}};
 const Source=({href=party,children})=><a className="assessment-source" href={href} target="_blank" rel="noreferrer">{children||t('查看官网依据','Official source')} <ExternalLink size={13}/></a>;
 const exportBrief=()=>{const brief={customer:'Orange Wheels',origin:'manual-public-research',reviewedAt:'2026-09-10',sources:[party,contact],confirmedDemand:false,concept:'Jungle exploration tent for a single-venue birthday pilot',questions:['Who owns purchasing?','Existing props or outsourced production?','Space and target ages?','Budget and schedule?'],deliverables:['Scene mockup after space confirmation','Theme variation','Cleaning and storage diagram','Short proposal PDF'],factoryChecks:['Dimensions and structure','Material and cleaning suitability','Commercial-use requirements','Sample cost and lead time'],teamNote:note};const url=URL.createObjectURL(new Blob([JSON.stringify(brief,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Orange-Wheels-material-brief.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(t('需求包已导出；未发送给软件一','Brief exported; not sent to software one'));};
 return <article className="assessment"><div className="assessment-back"><button onClick={onBack}><ArrowLeft size={16}/>{t('返回客户工作台','Back to customers')}</button><span>{t('完整评估样板 · 公开资料研究','Assessment sample · Public-source research')}</span></div>
 <header className="assessment-header"><div className="assessment-monogram">OW</div><div className="assessment-title"><h1>Orange Wheels</h1><p><MapPin size={15}/>{t('阿联酋 · 儿童游乐场连锁','UAE · Children’s play venue chain')}</p><div className="assessment-tags"><span>{t('主题派对','Themed parties')}</span><span>{t('单店试用切入','Single-venue pilot')}</span><span>{t('尚未联系','Not contacted')}</span></div></div><button className={'btn '+(saved.priority?'secondary':'')} onClick={()=>save({...saved,note,priority:!saved.priority})}><Bookmark size={16}/>{saved.priority?t('已标记重点 · 取消','Priority saved · Undo'):t('标记为重点','Mark as priority')}</button></header>
 <div className="assessment-summary"><div><h2>{t('值得联系，但先验证场景，再投入设计。','Worth contacting. Validate the use case before designing.')}</h2><p>{t('建议以“丛林探险营地”切入主题派对，先确认采购负责人、场地和现有道具。当前没有已确认的帐篷采购需求。','Explore a jungle-camp concept for parties. First confirm the buyer, space and existing props. No tent purchase requirement is confirmed.')}</p></div><div className="assessment-confidence"><span>{t('人工研究建议','Research recommendation')}</span><strong>{t('优先核实','Qualify first')}</strong><small>{t('AI 评分未运行','AI scoring not run')}</small></div></div>
 <nav className="assessment-nav" aria-label={t('评估目录','Assessment sections')}>{sections.map(([id,zh,eng])=><a key={id} href={'#ow-'+id} onClick={e=>{e.preventDefault();document.getElementById('ow-'+id)?.scrollIntoView({behavior:'smooth'});}}>{t(zh,eng)}</a>)}</nav>
 <div className="assessment-layout"><div className="assessment-main">
 <section id="ow-overview" className="assessment-section"><h2>{t('客户在做什么','What the customer does')}</h2><div className="assessment-overview"><dl><div><dt>{t('经营内容','Business')}</dt><dd>{t('儿童游乐与主题生日派对','Children’s play and themed birthdays')}</dd></div><div><dt>{t('本次研究门店','Venue to explore')}</dt><dd>Circle Mall · JVC · Dubai<small>{t('官网列址：商场二层。尚未确认该店的采购权限。','Official listing: second floor. Purchasing authority unverified.')}</small></dd></div><div><dt>{t('可见业务信号','Visible signal')}</dt><dd>{t('可定制主题、独立派对房','Customizable themes and a private party room')}</dd></div><div><dt>{t('目标年龄 / 预算','Target age / Budget')}</dt><dd>{t('待向客户确认','To confirm with the customer')}</dd></div></dl><figure>{failedImage?<div className="assessment-image-fallback">{t('官网图片暂不可用，请打开来源查看','Image unavailable. Open the source to view.')}</div>:<><span className="assessment-loading" hidden={imageLoaded}>{t('正在读取官网主题图…','Loading official theme image…')}</span><img onLoad={()=>setImageLoaded(true)} src={image} alt={t('Orange Wheels 官网丛林派对主题图片','Jungle party theme from Orange Wheels website')} onError={()=>setFailedImage(true)}/></>}<figcaption>{t('客户官网主题图 · 非我方设计','Customer’s theme image · Not our design')} <Source/></figcaption></figure></div><Source href={contact}>{t('核对门店位置与公开电话','Check venue and public phone')}</Source></section>
 <section id="ow-evidence" className="assessment-section"><div className="assessment-section-head"><h2>{t('为什么值得跟进','Why follow up')}</h2><span>{t('事实 → 推测 → 方案','Fact → Hypothesis → Proposal')}</span></div><div className="evidence-chain"><div><span className="evidence-kind fact"><CheckCircle2 size={14}/>{t('已核实事实','Verified fact')}</span><h3>{t('已有丛林与太空主题','Jungle and space themes exist')}</h3><p>{t('官方派对页列出这些主题，且说明主题可定制。','The party page lists these themes and offers customization.')}</p><Source/></div><ArrowRight className="chain-arrow" size={20}/><div><span className="evidence-kind hypothesis">{t('需求推测','Hypothesis')}</span><h3>{t('可能接受新增互动场景','A new play scene may fit')}</h3><p>{t('帐篷可能成为故事中的营地，但现有布景是否足够，仍需确认。','A tent could become a story’s camp; existing props may already meet the need.')}</p></div><ArrowRight className="chain-arrow" size={20}/><div><span className="evidence-kind proposal">{t('我方建议','Our proposal')}</span><h3>{t('先试一个主题、一家店','Pilot one theme at one venue')}</h3><p>{t('先做场地适配草案；得到需求反馈后再投入专属设计与打样。','Check the footprint first. Invest in custom design and sampling after feedback.')}</p></div></div><div className="assessment-reasons"><div><h3>{t('提高优先级的因素','Reasons to prioritize')}</h3><ul><li>{t('产品能对应已有主题，提案切入点明确。','The product connects to an existing theme.')}</li><li>{t('多地门店提供后续复制的可能，但不是已确认订单。','Multiple venues offer possible expansion, not confirmed orders.')}</li></ul></div><div><h3>{t('降低确定性的因素','Reasons for caution')}</h3><ul><li>{t('未发现公开帐篷采购需求；预算和时间未知。','No public tent procurement need found; budget and timing unknown.')}</li><li>{t('可能已有供应商，或由活动公司统一提供道具。','Props may come from an existing supplier or event agency.')}</li></ul></div></div></section>
 <section id="ow-channels" className="assessment-section"><h2>{t('渠道状态不能只看一个颜色','Channel evidence behind the colors')}</h2><p className="assessment-muted">{t('“已找到渠道”与“运营成熟度”分别判断；没有最新内容证据，不强行标绿或紫。','Channel discovery and operational maturity are separate. No green or purple rating without content evidence.')}</p><div className="assessment-channel-list">{[[t('官网','Website'),t('已找到并阅读','Found and reviewed'),t('主题与门店资料可读；近月更新及完整品牌能力未核验。','Themes and venue details reviewed; recent updates and brand capabilities unverified.')],[t('公开电话','Public phone'),'800 672 643',t('阿联酋本地电话；尚未拨打，未确认采购联系人。','UAE local number; not called, buyer not identified.')],['Email / WhatsApp',t('待核验','Unverified'),t('本轮没有核实可用于供应商接洽的专用入口。','No supplier-specific contact verified in this review.')],['Instagram / Facebook / LinkedIn',t('待核验','Unverified'),t('未完成账号归属、内容质量和最近更新时间核查。','Ownership, content quality and latest activity not checked.')]].map(([name,status,detail])=><div key={name}><strong>{name}</strong><span>{status}</span><p>{detail}</p></div>)}</div><Source href={contact}/></section>
 <section id="ow-proposal" className="assessment-section"><h2>{t('建议卖什么：丛林探险营地','What to propose: a jungle exploration camp')}</h2><p>{t('这是待验证的产品方向，不是已经定稿的款式。','A concept to validate, not a finalized product.')}</p><div className="assessment-proposal"><div><h3>{t('体验用途','Experience')}</h3><p>{t('把帐篷作为任务出发点、故事角或拍照场景。是否允许儿童进入，按年龄、空间及场馆要求确认。','Use a tent as a mission base, storytelling corner or photo scene. Confirm permitted use with the venue.')}</p></div><div><h3>{t('建议配置','Suggested configuration')}</h3><p>{t('可更换主题布套、便于清洁的表面、配件替换与收纳方案。尺寸和结构等工厂核实后再定。','Replaceable theme covers, cleanable surfaces, spare parts and storage. Factory review determines structure and size.')}</p></div><div><h3>{t('先让工厂回答','Factory checks first')}</h3><p>{t('材料与清洁适用性、结构稳定性、商用要求、打样费用、交期与运输体积。当前都未确认。','Materials, cleaning, stability, commercial-use requirements, sample cost, timing and shipping volume remain unconfirmed.')}</p></div></div></section>
 <section id="ow-next" className="assessment-section"><h2>{t('下一步怎么推进','How to proceed')}</h2><ol className="assessment-steps"><li><strong>{t('找到采购角色','Identify the buyer')}</strong><p>{t('通过公开电话询问由总部、门店还是活动供应商负责主题道具。','Ask whether head office, the venue or an event agency purchases props.')}</p></li><li><strong>{t('确认四个条件','Confirm four conditions')}</strong><p>{t('是否需要新增主题；现有道具情况；可用尺寸和年龄；预算与计划时间。','New theme needs; existing props; footprint and age group; budget and timing.')}</p></li><li><strong>{t('达到条件再做专属物料','Commission materials after qualification')}</strong><p>{t('确认使用场景、负责人及空间条件后，再给软件一制作场景方案。','Confirm use case, owner and space before sending a brief to software one.')}</p></li></ol><label className="field-label">{t('人工备注 / 联系后的反馈','Team notes / Feedback after contact')}<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder={t('记录真实回复，不把推测当成客户要求…','Record actual replies; keep hypotheses separate…')}/></label><button className="btn secondary" onClick={()=>save({...saved,note})}>{t('保存备注','Save notes')}</button></section>
 <section id="ow-brief" className="assessment-section"><h2>{t('给软件一的制作任务','Material brief for software one')}</h2><div className="assessment-brief"><div><h3>{t('待制作','Deliverables')}</h3><p>{t('场地适配 Mockup、主题换装示意、收纳清洁示意、简版提案 PDF。','A venue mockup, theme variations, storage/cleaning diagram and short proposal PDF.')}</p></div><div><h3>{t('还缺的输入','Missing inputs')}</h3><p>{t('场地照片与尺寸、品牌素材使用授权、工厂确认参数。官网原图仅作研究依据。','Venue photos and dimensions, brand asset permission and factory specifications. Website images are research references only.')}</p></div></div><button className="btn" onClick={exportBrief}><Download size={16}/>{t('导出制作需求包','Export material brief')}</button><small>{t('仅导出文件，尚未连接软件一，不会自动发送。','Exports a file only; software one is not connected. Nothing is sent.')}</small></section>
 </div><aside className="assessment-sidebar"><h3>{t('跟进决策','Follow-up decision')}</h3><p className="assessment-decision">{t('先核实，再设计','Qualify, then design')}</p><p>{t('主题契合明确，采购意向未知。建议先做一次需求沟通。','Clear thematic fit, unknown buying intent. Start with a needs conversation.')}</p><hr/><h3>{t('已知 / 未知','Known / Unknown')}</h3><div className="assessment-check"><CheckCircle2 size={16}/>{t('官网主题业务','Official theme offering')}</div><div className="assessment-check"><CheckCircle2 size={16}/>{t('门店与公开电话','Venue and public phone')}</div><div className="assessment-check pending"><HelpCircle size={16}/>{t('采购负责人、预算、时间','Buyer, budget and timing')}</div><div className="assessment-check pending"><HelpCircle size={16}/>{t('场地尺寸、产品要求','Space and specifications')}</div><hr/><p><Phone size={15}/> 800 672 643</p><Source href={contact}>{t('打开公开联系页','Open contact page')}</Source><hr/><small>{t('资料核对：2026-09-10。人工整理的真实客户样板；未运行自动采集或 AI 评分，尚未联系客户。','Reviewed 2026-09-10. Manually researched real-customer sample. No automated collection or AI score; customer not contacted.')}</small></aside></div><div className="assessment-status" role="status">{message}</div></article>;
}
