import CustomerScore from './CustomerScore.jsx';
import React,{useState,useRef} from 'react';
import {mergeVerification} from './channel-verification.js';
export default function SkillAssessment({customer:c,en,update,children}){
 const latest=useRef(c);latest.current=c;
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const t=(a,b)=>en?b:a;
 async function run(){setBusy(true);setError('');try{const r=await fetch('/api/assess',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:c.id,name:c.name,sources:c.sources,en})});const d=await r.json();if(!r.ok)throw Error(d.code);if(d.customerId!==c.id)throw Error('CUSTOMER_MISMATCH');const {verification,...report}=d;update(c.id,{...(verification?mergeVerification(latest.current,verification):{}),assessmentRuns:[...(latest.current.assessmentRuns||[]),report]});}catch(e){setError(t('本轮未生成成功，原有评估保留，请重试。原因：','Generation failed; previous assessments preserved. Please retry. Reason: ')+e.message);}finally{setBusy(false);}}
 const runs=c.assessmentRuns||[];
 const renderRun=r=><div><p style={{whiteSpace:'pre-wrap'}}>{r.text}</p><details><summary>{t('来源与版本','Sources & version')}</summary><small>{r.generatedAt} · {t('规则','Rules')} {r.ruleVersion.slice(0,12)} · {t('证据','Evidence')} {r.evidenceVersion.slice(0,12)} · {r.model}</small><ul>{r.sources.map(s=><li key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.id} · {s.url}</a></li>)}</ul></details></div>;
 return <section id="ca-fit" className="assessment-section"><h2>{t('评估与联系方案','Assessment & outreach')}</h2><button className="btn" disabled={busy||c.demo} onClick={run}>{busy?t('正在生成完整评估…','Generating full assessment…'):t('生成完整评估','Generate full assessment')}</button>{error&&<p role="alert">{error}</p>}{runs.length?renderRun(runs.at(-1)):children}{(runs.length>0||c.collection?.analysis)&&<details><summary>{t('历史与初始参考','History & initial reference')}</summary>{runs.length>0&&children}{runs.slice(0,-1).reverse().map(r=><details key={r.generatedAt}><summary>{r.generatedAt}</summary><CustomerScore customer={{...c,assessmentRuns:[r]}} en={en} compact/>{renderRun(r)}</details>)}{c.collection?.analysis&&<details><summary>{t('采集时的早期 AI 初评','Earlier collection analysis')}</summary><p style={{whiteSpace:'pre-wrap'}}>{c.collection.analysis.text}</p></details>}</details>}<small>{t('研究建议不等于客户已确认需求；人工备注和素材计划分别保存。','Research suggestions are not confirmed buying needs. Team notes and material plans are stored separately.')}</small></section>;
}
