import React,{useState,useEffect} from 'react';
export default function SkillSettings({en}){
 const t=(a,b)=>en?b:a;
 const [password,setPassword]=useState(''),[rules,setRules]=useState(''),[unlocked,setUnlocked]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[hidden,setHidden]=useState(false);
 const lock=()=>{setUnlocked(false);setRules('');setPassword('');setMessage('');};
 useEffect(()=>{const blur=()=>setHidden(true),focus=()=>setHidden(false);window.addEventListener('blur',blur);window.addEventListener('focus',focus);return()=>{window.removeEventListener('blur',blur);window.removeEventListener('focus',focus);};},[]);
 useEffect(()=>{if(!unlocked)return;const id=setTimeout(lock,5*60*1000);return()=>clearTimeout(id);},[unlocked]);
 async function submit(action){setBusy(true);setMessage('');try{const r=await fetch('/api/skill',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,action,...(action==='save'?{rules}:{})})});const data=await r.json();if(!r.ok){setMessage(r.status===401?t('密码不正确','Incorrect password'):t('规则服务尚未配置，请配置服务端密码与存储。','Configure the server password and rule storage first.'));if(r.status===401){setUnlocked(false);setRules('');setPassword('');}return;}setRules(data.rules);setUnlocked(true);setMessage(action==='save'?t('规则已保存；下一次 Skill 评估使用新版本。','Rules saved; the next Skill assessment uses the new version.'):t('已解锁，5分钟后自动锁定。','Unlocked. Automatically locks after 5 minutes.'));}catch{setMessage(t('连接失败，请检查服务','Connection failed. Check the server.'));}finally{setBusy(false);}}
 return <section className="panel skill-settings"><span className="eyebrow">{t('受限访问','RESTRICTED ACCESS')}</span><h2>{t('AI 适配分析与评分 Skill','AI fit & scoring Skill')}</h2><p>{t('统一管理客户适配依据与评分规则。规则用于客户价值与联系方案，暂不生成数字评分。','Manage fit criteria and scoring rules. Rules guide customer value and outreach; numeric scoring is not enabled.')}</p>{!unlocked?<form onSubmit={e=>{e.preventDefault();submit('read');}}><label className="field-label">{t('访问密码','Access password')}<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} required maxLength="256"/></label><button className="btn" disabled={busy}>{t('解锁配置','Unlock configuration')}</button></form>:<><div className="protected-rules" onCopy={e=>e.preventDefault()} onCut={e=>e.preventDefault()} onContextMenu={e=>e.preventDefault()}><label className="field-label">{t('分析与评分规则','Analysis & scoring rules')}<textarea aria-label={t('分析与评分规则','Analysis & scoring rules')} rows="10" maxLength="30000" value={hidden?'':rules} disabled={hidden} placeholder={hidden?t('窗口失焦，内容已隐藏','Content hidden while unfocused'):t('填写商定后的适配与评分规则…','Enter the agreed fit and scoring rules…')} onChange={e=>setRules(e.target.value)}/></label><small>{t('内部策略 · 仅限授权使用','Internal strategy · Authorized use only')}</small></div><div className="actions"><button className="btn" disabled={busy} onClick={()=>submit('save')}>{t('保存规则','Save rules')}</button><button className="btn secondary" onClick={lock}>{t('锁定','Lock')}</button></div></>}<p role="status">{message}</p><small>{t('限制复制、失焦隐藏与自动锁定仅减少泄露风险，无法阻止系统截图或拍照。','Copy restrictions, focus masking and auto-lock cannot prevent system screenshots or photography.')}</small></section>;
}
